language: node_js
node_js:
- '0.11'
env:
  global:
  - secure: lXasZW1eEAGVZcXkSGBgVeJOyBJoKt8RX4kANJbvOIOSsw3PutpSRO5xyhFjcFObXIqVnmHIj6wuvPV5RWRe9D93XfmKm69HCXal5xpIn1x+nmY3tZpc4fthuKbPW8jsIl63x6w0fs+1drX3+mu5U45qIYoQF+YBKpUV2C/yIOw=
  - secure: Xz8RS1U6erMFa86q1ekXQ1h+B1TnCBBMqe2JB2dLsWS2FbJv7LAdbD6d58xozO6b0q1h1E+uvI+wKi/5mlnTJb9obiapLgwtdTK6vqf9M4Cd4xr/cdLqxN2qYaq9j5nc8dHNBoCWuRX1Kb8mj79nyRPOXOoIZ+8hd/uLHncZJ70=
addons:
  sauce_connect: true
before_script:
- npm install gulp -g
- gulp serve &
