language: node_js
node_js:
- '0.11'
env:
  global:
  - secure: mPth+220yvtXmWjf2RoXbz095+TiqAWEMalIJMD7qgPsQ2OQrTCSs6dEroPkGrUSEzdS294D6n15hPkMjtynbqBe6fpzXtwvYF9jHV/e/4bvQTzhmLDVbVQNevgyutp9cWYxthVaEoEeABgfer7b8Dj2qiVzBKVTQIZh0O7gOqQ=
  - secure: b7qJLVnocvWcJfxFdTFXp5h53s5FWGndMRCFw6lugxNqWwUUzcomq/E0SrtpmQCAFAsK9UnfsYS4xYR+pMxuzof9cNYkUk7aFijI23oew8caZE6eYoEXMXCqWm/6XfUFN281mlqVS805wjsX6K0HSWTgduu1DuUJPIFRFq6jJHw=
addons:
  sauce_connect: true
install:
- npm install gulp -g
- npm install
before_script:
- gulp serve &
